drug_consumption/urls.py
from django.urls import path
from .views import (admin_register, patient_register, UserLoginView, 
                    logout, index, DatasetTableCreateView, DatasetTableListView,user_list, 
                    DatasetTableDetailView, DatasetTableUpdateView, delete_view, predict,ResultListView) 
from django.contrib.auth.views import LogoutView
from django.conf import settings
app_name = "drug_consumption"
urlpatterns = [
    # Admin Perspective
    path('admin-register/',admin_register,name="register-admin"),
    # Patient Perspective
    path('patient-register/',patient_register,name="register-patient"),
    # User
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page="drug_consumption:index"), name="logout"),
    path('',index, name='index'),
    
    # Dataset Perspective
    path('drug-data-create/',DatasetTableCreateView.as_view(),name='drug_data_create'),
    path("drug-data-list/",DatasetTableListView.as_view(),name="drug_data_list"),
    path('drug-data-details/<int:pk>/', DatasetTableDetailView.as_view(),name="drug_data_details"),
    path('drug-data-update/<int:pk>/',DatasetTableUpdateView.as_view(), name="drug_data_update"),
    path("drug-data-delete/<int:pk>/",delete_view, name="drug_data_delete"),
    # Result
    path("predict/<int:pk>/",predict, name='predict'),
    path('results/',ResultListView.as_view(), name='patient_result_list'),
    path("patients/",user_list,name="patient_list"),
]

drugtect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('drug_consumption.urls')),
]

drug_consumption/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
# Creating the model for the Patient
class Admin(models.Model):
    admin = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10)
    
    def __str__(self):
        return f'{self.admin.username}'
    
class Patient(models.Model):
    patient = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ])
    gender_choices=[('M','Male'),('F','Female')]
    gender= models.CharField(max_length=7,choices=gender_choices)
    managed_by = models.ForeignKey(Admin, on_delete=models.CASCADE)
# creating the model for the Dataset Table
    def __str__(self):
        return f'{self.patient.username}'

class DatasetTable(models.Model):
    datasetmodel=models.ForeignKey(Patient,on_delete=models.CASCADE)
    nscore = models.FloatField(
              validators=[
            MaxValueValidator(3.5),
            MinValueValidator(-4)
        ])
    escore = models.FloatField(
          validators=[
            MaxValueValidator(3.5),
            MinValueValidator(-3.5)
        ]
    )
    oscore = models.FloatField(
          validators=[
            MaxValueValidator(3.5),
            MinValueValidator(-3.5)
        ]
    )
    ascore = models.FloatField(
          validators=[
            MaxValueValidator(3.5),
            MinValueValidator(-3.5)
        ]
    )
    cscore = models.FloatField(
          validators=[
            MaxValueValidator(3.5),
            MinValueValidator(-3.5)
        ]
    )
    ethnicity_choices = [('White',"White"), 
                         ('Other','Other',),
                         ('Mixed-White/Black','Mixed-White/Black'),
                         ('Asian','Asian'),
                         ('Mixed-White/Asian','Mixed-White/Asian'),
                         ('Black','Black'),
                         ('Mixed-Black/Asian','Mixed-Black/Asian')
                         ]
    ethnicity = models.CharField(max_length=20, choices=ethnicity_choices)
    impulsive = models.FloatField(validators=[
            MaxValueValidator(3.0),
            MinValueValidator(-3.0)
        ]
    )
    drug_choices = [("coke","coke"),
                    ("heroin","heroin"),
                    ("mushroom","mushroom"),
                    ("lsd","lsd")]
    drug_type = models.CharField(max_length=20,choices=drug_choices)
    
# Creating the model for the Result 
class Result(models.Model):
    result = models.OneToOneField(DatasetTable,on_delete=models.CASCADE)
    classification_status = models.BooleanField(default=False)
    consumption_status = models.CharField(max_length=10,null=True,default=None)
    # consumption_status = models.BooleanField(null=True,default=None)

drug_consumption/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Admin, Patient, DatasetTable, Result

class PatientModelForm(UserCreationForm):
    email = forms.EmailField()
    class meta:
        model = User
        fields = ['email','username','password1','password2']
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already used")
        return email    
    
    def save(self, commit=True):
        user = super(PatientModelForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        # print(user.email)
        if commit:
            user.save()
        return user
    
    
class AdminModelForm(UserCreationForm):
    email = forms.EmailField()
    class meta:
        model = User
        fields = ['email','username','password1','password2']
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already used")
        return email    
    
    def save(self, commit=True):
        user = super(AdminModelForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        # print(user.email)
        user.is_staff = True
        if commit:
            user.save()
        return user
    
    
class AdminForm(forms.ModelForm):
    class Meta:
        model = Admin
        exclude = ['admin',]
        
class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        # fields = ['exclude']
        exclude = ['patient','managed_by']
        



# creating a form
class DatasetTableForm(forms.ModelForm):
    class Meta:
        model = DatasetTable
        exclude = ['datasetmodel']
		# specify fields to be used
		

drug_consumption/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from .forms import AdminModelForm, AdminForm, PatientForm, PatientModelForm, DatasetTableForm
from .models import Admin, Patient, DatasetTable, Result
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .utils import Model

# Create your views here.

def admin_register(request): 
    if request.method == "POST":
        user_form = AdminModelForm(request.POST)
        if user_form.is_valid():
            admin_form = AdminForm(request.POST)
            if admin_form.is_valid():
                try:
                    admin_user = user_form.save()
                    phone = admin_form.cleaned_data['phone']
                    Admin.objects.create(admin = admin_user, phone=phone)
                    return redirect('drug_consumption:index')
                except Exception:
                    return redirect('drug_consumption:index')
                    # return redirect("drug_consumption:index")
    elif request.method =="GET":
        user_form = AdminModelForm()
        admin_form = AdminForm()
        context = {'userform':user_form, "adminform":admin_form}
        return render(request, 'drug_consumption/admin_registration.html',context)


@login_required
def patient_register(request): 
    if request.method == "POST":
        user_form = PatientModelForm(request.POST)
        patient_form = PatientForm(request.POST)
        # print(user_form)
        # print(admin_form)
        if user_form.is_valid():
            # print(user_form.cleaned_data)
            if patient_form.is_valid():
                patient_age = patient_form.cleaned_data['age']
                patient_gender = patient_form.cleaned_data['gender'] 
                # print(admin_phone)
                patient_user = user_form.save()
                # print(patient_user)
                admin = request.user.admin
                Patient.objects.create(patient = patient_user, age=patient_age, gender = patient_gender, managed_by=admin)
            print("Patient created sucessfully.")
            # return HttpResponse("Hello Patient created.")
            return redirect('drug_consumption:index')
    elif request.method =="GET":
        user_form = PatientModelForm()
        patient_form = PatientForm()
    context = {'userform':user_form, "adminform":patient_form}
    return render(request, 'drug_consumption/admin_registration.html',context)

class UserLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'drug_consumption/login.html'
    def get_success_url(self):
        return reverse_lazy('drug_consumption:index')
        # return HttpResponse("login") 
    
    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))
    

@login_required
def logout_view(request):
    logout(request)
    return redirect('drug_consumption:index')


def index(request):
    context = {}
    return render(request, 'drug_consumption/index.html',context)
 
class DatasetTableCreateView(CreateView):
 
    # specify the model for create view
    model = DatasetTable
 
    # specify the fields to be displayed
    success_url = reverse_lazy("drug_consumption:index")
    form_class = DatasetTableForm
    
    def form_valid(self, form):
        form.instance.datasetmodel = self.request.user.patient
        self.object = form.save()
        return super().form_valid(form)

class DatasetTableListView(ListView):
    model = DatasetTable
    
    def get_queryset(self):
        queryset = self.model._default_manager.all()
        print(self.request.user)
        if not self.request.user.is_staff:
            print(self.request.user.patient)
            patient = self.request.user.patient
            queryset = DatasetTable.objects.filter(datasetmodel = patient)
        else:
            # Admin user
            admin = self.request.user.admin
            print(admin)
            queryset = DatasetTable.objects.filter(datasetmodel__managed_by = admin)
        return queryset

        
class DatasetTableDetailView(DetailView):
    # specify the model to use
    model = DatasetTable
    
class DatasetTableUpdateView(UpdateView):
    # specify the model you want to use
    model = DatasetTable
    form_class = DatasetTableForm
    
    def get_success_url(self):
        return reverse_lazy('drug_consumption:drug_data_list')
    
def delete_view(request, pk):
    context ={}
    obj = get_object_or_404(DatasetTable, id = pk)
    obj.delete()
    return redirect("drug_consumption:drug_data_list")


def predict(request,pk):
    # Function used by machine learning.
    obj = get_object_or_404(DatasetTable, id = pk)
    classification_status = True
    consumption_status = "C1"
    try:
        r1 = Result.objects.create(result = obj, classification_status= classification_status, consumption_status=consumption_status)
        print("Object Created.")
    except:
        r1 = obj.result
    print(request.user.patient.age)
    model = Model("mushroom")
    model.set_values(obj.nscore,obj.escore,obj.oscore,obj.ascore,obj.cscore,obj.impulsive,request.user.patient.gender,request.user.patient.age,obj.ethnicity)
    prediction = model.predict_data()
    r1.consumption_status = str(prediction[0])
    context = {}
    context['prediction']  = r1.consumption_status
    print(context)
    return JsonResponse(context, status=200)

class ResultListView(ListView):
    model = Result
    
    def get_queryset(self):
        queryset = self.model._default_manager
        try:
            user = self.request.user.patient
        except:
            print("User is admin.")
        else:
            # loan = LoanDetails.objects.filter(loan_request__managed_by = employee)
            return queryset.filter(result__datasetmodel = user)
    
class ResultAllListView(ListView):
    model = Result
    template_name = "drug_consumption/result_all.html"
    
    def get_queryset(self):
        queryset = self.model._default_manager
        try:
            user = self.request.user.admin
        except:
            print("User is admin.")
        else:
            return queryset.filter(result__datasetmodel__managed_by = user)

def user_list(request):
    current_user = request.user.admin
    patients = Patient.objects.filter(managed_by = current_user)
    print(patients)
    context = {}
    context['patients'] = patients
    # for i in patients
    return render(request,'drug_consumption/patients_list.html', context)
    

drug_consumption/templates/drug_consumption/datasettable_list.html
{% comment %} {% if not user.is_staff %}

    <a href="{% url 'drug_consumption:drug_data_create'%}">Create</a> <br><br>
    <!-- Iterate over object_list -->
    <ul>
    {% for object in object_list %}
    <!-- Display Objects -->
        {% if not object.result %}
            <li>{{ object.datasetmodel }}</li>
            <li>{{ object.nscore }}</li>
            <li>{{ object.escore }}</li>
            <li>{{ object.oscore }}</li>
            <a href="{% url 'drug_consumption:drug_data_details' object.id%}">In Details</a> <br><br>
            <a href="{% url 'drug_consumption:drug_data_update' object.id%}">Update</a><br><br>
            <a href="{% url 'drug_consumption:drug_data_delete' object.id%}">Delete</a><br><br>
            <hr>
        {% endif %}
    <!-- If object_list is empty  -->
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'drug_consumption:patient_result_list' %}">View Predictions</a><br><br>
{% else %}
Hello Admin<br>
<ul>
    {% for object in object_list %}
    <!-- Display Objects -->
        {% if not object.result %}
            <li>{{ object.datasetmodel }}</li>
            <li>{{ object.nscore }}</li>
            <li>{{ object.escore }}</li>
            <li>{{ object.oscore }}</li>
            <a href="{% url 'drug_consumption:drug_data_details' object.id%}">In Details</a> <br><br>
            <hr>
        {% endif %}
    <!-- If object_list is empty  -->
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}
</ul>

{% endif %}

<a href="{% url 'drug_consumption:logout'%}">Logout</a><br><br> {% endcomment %}



 {% load static %}
 <!DOCTYPE html>
 <html lang="en">
 
 <head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Drug Data List-DrugTect</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
 
    <link rel="icon" type="image/png" href="{% static 'images/icons/drug_detect.png' %} "/>
    <!-- bootstrap css -->
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} ">
    <!-- style css -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %} ">
    <!-- Responsive-->
    <link rel="stylesheet" href=" {% static 'css/responsive.css' %} ">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href=" {% static 'css/jquery.mCustomScrollbar.min.css' %} ">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'css/jquery.mCustomScrollbar.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'css/owl.theme.default.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/drugdatalist.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
 </head>
 
 <body>
    <!-- header section start -->
    <div class="data_table_dl">
       <nav class="navbar">
          <h2 class="logo"><a href="index.html">DrugTect</a></h2>
       </nav>
       <!-- header section end -->
       <!-- banner section start -->
       <div class="carousel-inner">
          <div class="carousel-item active">
             <div class="banner_section">
                <div class="container">
                    <div class="row">
                       <div class="main-data">
                            
                                {% if not user.is_staff %}
                                <div>
                                    <a href="{% url 'drug_consumption:drug_data_create'%}">Create</a> <br><br>
                                </div>
                                <div>
                                    <div class="main-heading">Drug Data List</div>
                                </div>
                                <!-- Iterate over object_list -->
                                <div class="table">
                                    <div class="table-row table-head">
                                        <div class='p-1'>Patient Name</div>
                                        <div class='p-1'>N Score</div>
                                        <div class='p-1'>E Score</div>
                                        <div class='p-1'>O Score</div>
                                        <div class='p-1'>
                                            Action 1
                                        </div class='p-1'>
                                        <div class='p-1'>
                                            Action 2
                                        </div>
                                        <div class='p-1'>
                                            Action 3
                                        </div>
                                    </div>
                                {% for object in object_list %}
                                <!-- Display Objects -->
                                    {% if not object.result %}
                                    <div class="table-row">
                                        <div class='p-1'>{{ object.datasetmodel }}</div>
                                        <div class='p-1'>{{ object.nscore }}</div>
                                        <div class='p-1'>{{ object.escore }}</div>
                                        <div class='p-1'> {{ object.oscore }}</div>
                                        <div class='p-1'>
                                        <a href="{% url 'drug_consumption:drug_data_details' object.id%}">In Details</a> <br><br>
                                        </div>
                                        <div class='p-1'>
                                        <a href="{% url 'drug_consumption:drug_data_update' object.id%}">Update</a><br><br>
                                        </div>
                                        <div class='p-1'>
                                        <a href="{% url 'drug_consumption:drug_data_delete' object.id%}">Delete</a><br><br>
                                        </div>
                                    </div>
                                    {% endif %}
                                <!-- If object_list is empty  -->
                                {% empty %}
                                <li>No objects yet.</li>
                                {% endfor %}
                                </div>
                                <div>
                                <a href="{% url 'drug_consumption:patient_result_list' %}">View Predictions</a><br><br>
                                </div>
                            {% else %}
                            Hello Admin<br>
                            <div>
                                {% for object in object_list %}
                                <!-- Display Objects -->
                                    {% if not object.result %}
                                        <li>{{ object.datasetmodel }}</li>
                                        <li>{{ object.nscore }}</li>
                                        <li>{{ object.escore }}</li>
                                        <li>{{ object.oscore }}</li>
                                        <a href="{% url 'drug_consumption:drug_data_details' object.id%}">In Details</a> <br><br>
                                        <hr>
                                    {% endif %}
                                <!-- If object_list is empty  -->
                                {% empty %}
                                <li>No objects yet.</li>
                                {% endfor %}
                            </div>
                            
                            {% endif %}
                            
                            {% comment %} <a href="{% url 'drug_consumption:logout'%}">Logout</a><br><br> {% endcomment %}
                          </div>
                       </div>
                    </div>
                 </div>
          </div>
       </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright_section">
       <div class="container">
          <p class="copyright_text">2023 All Rights Reserved.</p>
       </div>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src=" {% static 'js/jquery.min.js' %} "></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %} "></script>
    <script src="{% static 'js/plugin.js' %} "></script>
    <!-- sidebar -->
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %} "></script>
    <script src="{% static 'js/custom.js' %} "></script>
    <!-- javascript -->
    <script src="{% static 'js/owl.carousel.js' %} "></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
 </body>
 
 </html>

drug_consumption/templates/drug_consumption/index.html
{% comment %} Hello: {{user}} <br>
 {% endcomment %}

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>DrugTect</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">

   <link rel="icon" type="image/png" href="{% static 'images/icons/drug_detect.png' %} "/>
   <!-- bootstrap css -->
   <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} ">
   <!-- style css -->
   <link rel="stylesheet" href=" {% static 'css/style.css' %} ">
   <!-- Responsive-->
   <link rel="stylesheet" href=" {% static 'css/responsive.css' %} ">
   <!-- fevicon -->
   <link rel="icon" href="images/fevicon.png" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href=" {% static 'css/jquery.mCustomScrollbar.min.css' %} ">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %} ">
   <link rel="stylesheet" href=" {% static 'css/jquery.mCustomScrollbar.min.css' %} ">
   <link rel="stylesheet" href=" {% static 'css/owl.theme.default.min.css' %} ">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
</head>

<body>
   <!-- header section start -->
   <div class="header_section">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <h2 class="logo"><a href="{% url 'drug_consumption:index'%}">DrugTect</a></h2>
         <!-- <div class="logo"><a href="index.html"><img src="images/logo.png"></a></div> -->
         <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button> -->
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}

                {% if user.is_superuser %}
               <li class="nav-item">
                  <a  class="nav-link" href="admin/">Admin Panel</a>
               </li>
               <li class="nav-item">
                  <a  class="nav-link" href="{% url 'drug_consumption:logout'%}">Logout</a>
               </li>
               {% elif user.is_staff %}
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:register-patient'%}">Patient Registration</a>
               </li>
               <li class="nav-item ">
                  <a  class="nav-link" href="{% url 'drug_consumption:patient_list'%}">View Patient</a>
               </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:drug_data_list'%}">View Drug Results</a>
               </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:logout'%}">Logout</a>
               </li>
               {% elif not user.is_staff %}
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:drug_data_create'%}">Drug Prediction Create</a>
               </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:drug_data_list'%}">View Consumption</a>
               </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:logout'%}">Logout</a>
               </li>
               {% endif %}
               {% else %}
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:register-admin'%}">Admin Create</a>
               </li>
               <li class="nav-item ">
                  <a class="nav-link" href="{% url 'drug_consumption:login'%}">Login</a>
               </li>
               {%endif%}
            </ul>
         </div>
      </nav>
      <!-- header section end -->
      <!-- banner section start -->
      <div class="carousel-inner">
         <div class="carousel-item active">
            <div class="banner_section">
               <div class="container">
                  <div class="row">
                     <div class="col-md-6">
                        <h1 class="banner_taital">Drug <br><span style="color: #151515;">Tect</span></h1>
                        <p class="banner_text">Drugtect Where you can Predict whether one have Consume Drug Or Not</p>
                        <div class="btn_main">
                           {% comment %} <div class="more_bt"><a href="#">Register</a></div>
                           <div class="contact_bt"><a href="#">Login</a></div> {% endcomment %}
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="image_1"><img src="{% static 'images/drug.png' %} "></div>
                     </div>
                  </div>
               </div>
         </div>
      </div>
   </div>
   <!-- footer section end -->
   <!-- copyright section start -->
   <div class="copyright_section">
      <div class="container">
         <p class="copyright_text">2023 All Rights Reserved.</p>
      </div>
   </div>
   <!-- copyright section end -->
   <!-- Javascript files-->
   <script src=" {% static 'js/jquery.min.js' %} "></script>
   <script src="{% static 'js/popper.min.js' %} "></script>
   <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
   <script src="{% static 'js/jquery-3.0.0.min.js' %} "></script>
   <script src="{% static 'js/plugin.js' %} "></script>
   <!-- sidebar -->
   <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %} "></script>
   <script src="{% static 'js/custom.js' %} "></script>
   <!-- javascript -->
   <script src="{% static 'js/owl.carousel.js' %} "></script>
   <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</body>

</html>

drug_consumption/templates/drug_consumption/result_all.html
<ul>
    <a href="{% url 'drug_consumption:drug_data_create'%}">Create</a> <br><br>
    <!-- Iterate over object_list -->
    {% for object in object_list %}
    <!-- Display Objects -->
            <li>Consumption: {{ object.consumption_status }}</li>
            <li>Classification: {{ object.classification_status }}</li>
            <li>{{ object.result.oscore }}</li>
            <li>{{ object.result.ascore }}</li>
            <hr>
    <!-- If object_list is empty  -->
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}
</ul>